### ISSUE TITLE
[Request] Short installation guide

### ISSUE THREAD

**Issue by morethanhater** [NeverBehave/Tweet2Telegram#10]
Hello
Thank you, NeverBehave for this wonderful concept made in project
I open this issue to request a short installation guide for this github project.
Any proposes are strongly welcome.
Thank you.

**Comment by Misaka13514** [comment]
## How to use:

1. Fork
2. Checkout all variables in `.env.example`, fill in the GitHub project `settings -> secrets`


## Prerequisites

- `Twitter API KEY` and `ACCESS TOKEN`
  - Apply and create an APP https://developer.twitter.com/en/portal/dashboard
- Create a `gist` with content `{}`:
  - https://gist.github.com
  - The file name defaults to `data.json`
  - For example in `https://gist.github.com/NeverBehave/606d7e14436187b4d45e8657fafd40ab`
    - `606d7e14436187b4d45e8657fafd40ab` is the `GIST_ID`
- Apply for a Telegram Bot and join the group/channel you want to send to
  - [@Botfather](https://t.me/botfather)
  - Get channel ID, forward a channel message to [@JSONDumpBot](https://t.me/JSONDumpBot)
  - The `CHANNELBOT` variable corresponds to `BOT_TOKEN`
- `GIST_TOKEN` is a [GitHub token](https://github.com/settings/tokens), you need to tick the gist option
