### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by Misaka13514** [NeverBehave/Tweet2Telegram#3]
应该是同一条推文，已尝试
- [x] 多次运行验证
- [x] 更新Bot token与channel id

log:
- [#663](https://github.com/Misaka13514/Tweet2Telegram/runs/1986892249?check_suite_focus=true)
- [#664](https://github.com/Misaka13514/Tweet2Telegram/runs/1986961087?check_suite_focus=true)
- [#665](https://github.com/Misaka13514/Tweet2Telegram/runs/1987055608?check_suite_focus=true)

报错信息
```
Error:  consola.warning is not a function
134
  at src/index.js:44:35
135
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
136
  at async main (src/index.js:42:13)
```
猜测是无法获取推文（？）

**Comment by SagiriShiho** [comment]
同问题，并且报错一次，该次任务其余新推文全部都未发送，下次任务也并无重新发布

--log:
[#4](https://github.com/SagiriShiho/Tweet2Telegram/runs/1993584649?check_suite_focus=true)


--报错信息【NSFW】注意
``` 
[info] build message:  [ { caption:
     '<a href="https://twitter.com/akaroi_hato/status/1365606121432485899">Tweet</a> by <a href="https://twitter.com/akaroi_hato">@akaroi_hato</a> \n\n🐶💦 \n',
    parse_mode: 'html',
    type: 'video',
    media: 'https://video.twimg.com/tweet_video/EvObcDRVoAQ7-AM.mp4' } ]
Error:  consola.warning is not a function
  at src/index.js:44:35
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async main (src/index.js:42:13)
``` 


--猜测原因
猜测是TG抓取url失败，而导致程序发送失败，最终终结了该次任务
也导致了该次任务其余新推文全部都未发送，下次任务也并无重新发布


--解决方式1（图片方面）
图片方面，失败时可尝试更换另外一种图片url格式再发送，如 
```  'https://pbs.twimg.com/media/EvEKt42VEAAw8Uy.jpg?name=large' ``` 
改 
``` 
'https://pbs.twimg.com/media/EvEKt42VEAAw8Uy.jpg:large'
'https://pbs.twimg.com/media/EvEKt42VEAAw8Uy.jpg?name=orig'
'https://pbs.twimg.com/media/EvEKt42VEAAw8Uy.jpg:orig'
``` 
![20210227232841.png](https://i.loli.net/2021/02/27/E39HavjNXOitZSe.png)

至于视频方面暂时无法多url方式解决，建议失败时更换发送推文url


--解决方式2（并不方便）
适用官方(?)网页bot @WebpageBot 刷新网页缓存即可

**Comment by NeverBehave** [comment]
90df01301b1e82ef1e51d7997fd151fbb8898832

失败会重试5次，没有重试是因为报错的提示写错了导致提前终止

如果失败则推文不会重新推送，这个是设定，因为怕任务有重叠（在太短的间隔下）

P.S. github action最短5分钟间隔
