### ISSUE TITLE
推送失败时，建议更换图片URL格式再重试

### ISSUE THREAD

**Issue by SagiriShiho** [NeverBehave/Tweet2Telegram#4]
首先非常感谢作者的程序
但最近发现推送失败率比较多了

**--log:**
https://github.com/SagiriShiho/Tweet2Telegram/runs/2431320149?check_suite_focus=true

**--报错信息**
``` 
[info] tweet for:  { id: '1386268712483786759',
  link: 'https://twitter.com/yuukihagure/status/1386268712483786759',
  media:
   [ { media: 'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg?name=large',
       type: 'photo' } ],
  user: { username: 'yuukihagure', link: 'https://twitter.com/yuukihagure' },
  text: '#絵師100人展 ',
  nsfw: true }
[info] build message:  [ { caption:
     'https://twitter.com/yuukihagure/status/1386268712483786759 #possiblyNSFW\n#絵師100人展 \n',
    parse_mode: 'html',
    media: 'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg?name=large',
    type: 'photo' } ]
Error:  1386268712483786759 send failed after 5 retries
``` 

**--复现**
我尝试使用n8n.io程序自带TGbot功能以图片URL(photo_url)方式推送``` 'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg?name=large' ``` 
也失败并显示
``` 
ERROR: Telegram error response [400]: Bad Request: wrong file identifier/HTTP URL specified
``` 
![Snipaste_2021-04-25_21-21-20.png](https://i.loli.net/2021/04/25/8i3AbDYTfgu2pnv.png)

**--问题猜测**
TG第一次抓取图片URL失败，那么不手动刷新缓存情况下，再次推送还是会一直失败的
因此推送失败时，再重试5次，还是都会失败

**--解决方式1**
图片方面失败时可尝试更换另外一种图片url格式再重试，列如我这个错误地址为
``` 'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg?name=large' ``` 
改 
``` 
'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg:large'
'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg?name=orig'
'https://pbs.twimg.com/media/Ez0D6j_VUAIF91M.jpg:orig'
``` 
![Snipaste_2021-04-25_21-22-46.png](https://i.loli.net/2021/04/25/qRKhUboVpmFMigC.png)
![Snipaste_2021-04-25_21-21-54.png](https://i.loli.net/2021/04/25/hAZdoq8UcCKPE1k.png)
![Snipaste_2021-04-25_21-22-16.png](https://i.loli.net/2021/04/25/zqW7yCho5UExNaA.png)
这里我还是用n8n.io程序自带TGbot功能以图片URL(photo_url)方式推送测试

![Snipaste_2021-04-25_21-27-10.png](https://i.loli.net/2021/04/25/uVJBTaXfKvOCIML.png)
当然更直观的还是直接发送图片url，看看有没有预览图片

**--解决方式2（并不方便）**
使用官方(?)网页bot @WebpageBot ，发送网页URL，刷新缓存即可

**Comment by NeverBehave** [comment]
ok，晚点看看
如果只是换参数我觉得在后面随机加上一个时间戳就好了

**Comment by NeverBehave** [comment]
我差点忘了这回事，现在加一下
